maaslalani/slides

model/model.go

I had to guess what I missed here:
However, showing the error directly to the user is very helpful IMO. 🙂

Show markdown rendering error to user

---

README.md
cmd/root.go
examples/slides.md

Fixes #5 
- Allow using triple dashes as a slide separator
- Keep old slides separator for backward compatibility

Fix #5 Allow to use triple dashes as a slide separator

---

README.md
cmd/root.go

Fixes #15
This change allows users to pipe in slides from `stdin` which allows for
`curl`ing remote slides and presenting them as well as piping multiple files
into one (with `cat`) and much more.
```
curl http://example.com/slides.md | slides
```
This change also maintains backwards compatibility with the current API which
allows for users to simply specify a file name. In the future, it would be nice
to remove that in favour of simply reading the file from stdin.
Like so:
```
slides < examples/slides.md
```

Read slides from stdin

---

internal/code/code.go
internal/code/code_test.go

This PR adds a code package and Parse function in that package to extract code blocks from markdown.
This will be used to parse code from slides and later on to execute code blocks with the correct interpreters / compilers.

Add `code` package with `Parse` function (with tests)

---

internal/code/code.go
internal/code/execute_test.go
internal/code/languages.go

This PR allows `code.Block`'s to be executed
We can run an arbitrary code block for any one of the following languages:
* Bash
* Go
* Ruby
* Python
Note: This is still just package code and none of it is hooked up to actual execution of the program.
But, now that we have `code.Parse(markdown string) Block` and `code.Execute(code Block) Result` it should be
extremely straight forward to parse slide for code blocks and execute them.
Displaying the output will be the most tricky part.

Code block execution

---

README.md

go install needed "@latest"
required when current directory is not in a module.
Fixes
when doing
$  go install  
add "@latest".
- go snap installed version in ubuntu latest (go version go1.16.5 linux/amd64)
suggest Try 'go install github.com/maaslalani/slides@latest'

install required directory is not in a module

---

examples/code_blocks.md
internal/code/code.go
internal/code/code_test.go
internal/model/model.go

Fixes #9
Ability to execute code blocks by pressing <kbd>e</kbd> (Want to change this for security reasons).

Execute code on slides

---

internal/code/code.go
internal/code/code_test.go

Fix #39, allow code blocks without trailing new line to run

---

README.md
internal/model/model.go

Fixes #47
Fixes #48 
- Removes `~~~` as a slide delimiter

Remove `~~~` as a slide delimiter

---

internal/model/model.go

The output should be displayed as is instead of being rendered as Markdown.

Do not render output of code blocks as Markdown

---

examples/preprocess.md
internal/process/execute_test.go
internal/process/process.go
internal/process/process_test.go

Part of #51 
- Add parsing of code blocks to execute arbitrary commands
```
~~~sd Find Replace
Find
~~~
```
Slides will take any code block like above that specifies a command and will run the command and pass the block as `stdin`
The above gets pre-processed to:
```
Replace
```

Add pre-processing of slides

---

README.md
examples/import.md
examples/preprocess.md
internal/file/file.go
internal/file/file_test.go
internal/model/model.go
internal/process/process.go

Fixes #51 
- Allow arbitrary commands to be executed for pre-processing slides
- This allows for embedding graphs, diagrams, any output of any command, really
- This is a bit different than code execution because it entirely replaces the block of code with the output of the command with the input in the block.

Pre-process any commands

---

internal/process/execute_test.go

This patch updates the `sd Find Replace` test case to make use of `sed`
instead of `sd`. This should help tests pass on a wider range of
systems without introducing a testing dependency.
Fixes #60

EXECUTE: TEST: Use more common sed instead of sd

---

README.md

I noticed that the following links on the page(https://maaslalani.com/slides/) are not accessible:
Checkout the [example slides](./example)
Check out the provided [theme.json](../../styles/theme.json) to use as a base for your custom theme.
Fixes #...
- [example slides](https://github.com/maaslalani/slides/tree/main/examples)
- [theme.json](./styles/theme.json)

fix:link error in the website

---

internal/meta/meta.go
internal/meta/meta_test.go
internal/model/model.go

Fixes #https://github.com/maaslalani/slides/issues/77
- Allows preceeding `---`
- Removes dependencies on frontmatter
- Prevents crashing on slides with only valid YAML for first slide

fix: bug, preceeding ---, yaml comments

---

examples/custom_remote_theme.md
styles/styles.go

Fix #73, add support for fetching remote theme
- When a theme starts with "http://" or "https://", try fetch it from the internet.

Fix #73, add support for fetching remote theme

---

internal/meta/meta.go

Fixes #92
I suggest an implementation as described in the issue mentioned above. We used a temporary struct to parse the YAML, and then check its fields. If they were not set, we use a default value, otherwise, we use the parsed value.
The downside is that for every field in `Meta` we need a block such as:
```go
if tmp.NameOfTheField != nil {
m.NameOfTheField = *tmp.NameOfTheField
} else {
m.NameOfTheField = fallback.NameOfTheField
}
```
The good part is that we can decide the strategy and defaults for each field (for example, using OS's user name as a default for `author` as suggested in #87).

Fixes metadata fallback strategy

---

cmd/root.go
examples/metadata.md
internal/meta/meta.go
internal/meta/meta_test.go
internal/model/model.go

Fixes #87 by adding the fields `Author`, `Date` and `Numbering` in the `Meta` struct.
Not sure where/how to document what I had in mind, so I drafted this table:
| Field | Default | Behavior os the custom value |
|---|---|---|
| `Auhtor` | Current OS user's full name | The string from the YAML replaces the name (including an empty string) |
| `Date` | Today's date in the `YYYY-MM-DD` format | If the date passed is a valid form of `2006-01-02`, it is used to format today's date, otherwise, it just replaces the date with this string |
| `Numbering` | `"Slide %d / %d"` | If the value contains one occurrence of `%d` it is used in `fmt.Sprintf` with the current slide number; if it contains 2, with the current slide number first and the total slide number last; otherwise, it just replaces the …

Adds customization to the bottom metadata

---

go.mod
go.sum

Fixes #88
- just a `go.mod`/`go.sum` change to bump `glamour`.  If you're not keen on using an untagged version, I totally understand and will wait for their release process.  The version corresponds to [`49f2da7feda65ff4f68578b7f8d4eb2fb72e07ee`](https://github.com/charmbracelet/glamour/commit/49f2da7feda65ff4f68578b7f8d4eb2fb72e07ee), which is currently `HEAD` of `master`

bump glamour to fix bug in orderedList

---

.github/workflows/goreleaser.yml
.github/workflows/test.yml
go.mod
go.sum

- update build to use [latest go1.17](https://go.dev/blog/go1.17)
---
relates to Homebrew/homebrew-core#83413

build: bump to use go1.17

---

README.md
internal/meta/meta.go
internal/meta/meta_test.go

This PR addresses the issue #106, offering users the possibility to use standard `YYYY-MM-DD` format in the date metadata. It offers the following possibilities:
| Value  | Translates to |
|--------|---------------|
| `YYYY` | 2006          |
| `YY`   | 06            |
| `MMMM` | January       |
| `MMM`  | Jan           |
| `MM`   | 01            |
| `mm`   | 1             |
| `DD`   | 02            |
| `dd`   | 2             |

Uses custom date format YYYY-MM-DD

---

internal/process/process.go

Fixes #144 
- `s/CombinedOutput/Output/g`

fix: do not get `stderr` when preprocessing slides

---

README.md
examples/metadata.md
internal/meta/meta.go
internal/meta/meta_test.go
internal/model/model.go

Fixes #https://github.com/maaslalani/slides/issues/152
- Deprecates `2006-01-02` strings in favour of `YYYY-MM-DD` strings.
- Interprets all non-parse-able dates as static strings.

feat: ensure that date strings are not interpreted as January 2, 2006 formatted strings

---

examples/code_blocks.md
internal/code/code.go
internal/code/comments.go
internal/code/comments_test.go
internal/model/model.go

Fixes #135
- Ability to add comments that are not displayed to the user but used in the
execution of the program and when copying code blocks.

Code Comments to hide verbose code

---

examples/code_blocks.md
internal/code/languages.go

As of Java 11 a single file can be launched without explicitly
compiling, packaging and running the file in different steps.
In other words single-file source-code programs can be executed
with "java Program.java", where "Program.java" is the name of
the file to be executed.

feat: add support for java code execution

---

examples/code_blocks.md
internal/code/languages.go

Add support for [Swift](https://www.swift.org/) language. Tested that it works with common imports (`Foundation`).
- Support for the Swift language
- Adds a missing hline in the example

Add support for Swift

---

README.md
internal/navigation/navigation.go
internal/navigation/navigation_test.go

Add a keybind to navigate to the previous slide when the user presses
`N` (`Shift` + `n`).
This matches what you would intuitively expect when you're using to Vim
keybindings.

Bind `N` to navigate to previous slide

---

examples/code_blocks.md
internal/code/languages.go

This PR adds support for [fish (the Friendly Interactive SHell)](https://fishshell.com/) to code blocks  
I followed the example of [this PR](https://github.com/maaslalani/slides/commit/15248d2023f1b77c9139d436a8b1b949f47be75b) about adding support for zsh, but let me know if I missed something!

Add fish support for code blocks

---

internal/model/model.go

Fixes #231 
- Removes carriage returns from the .md file immediately after reading it
I would be skeptical that the solution is this simple, but I have verified that it works on both Windows and Linux (WSL Ubuntu) using slides.md as well as the two files attached in the issue (one with DOS line endings and the other with Unix line endings). 🤷🏽‍♂️

Fixes maaslalani/slides#231

---

README.md

The default Markdown processor for GitHub Pages doesn't process the contents of `<details>` blocks, resulting in raw Markdown in the output at https://maaslalani.com/slides/:
This PR instructs Kramdown to process Markdown in that block:

Enable Markdown processing in "details" block

---

README.md

This adds _presenterm_ as an alternative tool, as suggested by [@maaslalani](https://github.com/maaslalani/slides/issues/2#issuecomment-1752149352).

Add presenterm as an alternative tool

---

examples/code_blocks.md
internal/code/languages.go

Hi, very nice tool!
I was missing support for scala, so I've added a super simple implementation using scala-cli which will become the standard scala runner in scala version 3.5 really soon, so should be installed for most users
- added command to run scala code blocks using the `sc` filetype with scala-cli
- added example in `examples/code_blocks.md`

add scala support using scala-cli
