maaslalani/slides

model/model.go
Fixes #7
- Display the correct number of slides and current one
=> Fix #7 Display the correct number of slides and current one

.github/workflows/test.yml
- Adds golangci-lint on push/pr 
- Adds go test -race -v ./... on push/pr
=> Testing and linting in Github actions

go.mod, styles/styles.go
Fixes #24 
- Light mode support
- [No color](https://no-color.org/) support
=> Added light mode support and support for EnvNoColor

internal/model/model.go
Fixes #40
- J goes to the next slide
- K goes to the previous slide
=> Swap J and K controls

README.md, snap/snapcraft.yaml
- README has been updated to reflect snap installation
- Snap directory and `yaml` created
- Snap has been published the [Snap Store](https://snapcraft.io/slides)
I can continue to support the snap if you'd like but if you'd rather take full ownership and support it yourself, we can discuss steps to do so (very easy). 
This is an awesome application and I can see myself using it to impress the geekier people out there. :)
=> Snap has been created for slides

examples/code_blocks.md, internal/code/languages.go
Fixes #57
- Add node/js code execution
=> Add node/js code execution

examples/code_blocks.md, internal/code/languages.go
Thank you for this project. Please concider the pull request which append perl to the list of supported languages for code execution.
=> add perl code execution

internal/model/model.go
Fixes https://github.com/maaslalani/slides/issues/62
- Prevent crashes with short slides
=> Ensure slides has at least some content to prevent crashing

styles/styles.go
Fixes #71 
Tries to read theme files. On success, the theme will be loaded and applied. On failure, the previous behaviour will take effect.
=> Add handling logic for custom theme files

examples/code_blocks.md, internal/code/languages.go
Fixes #75
- Adds lua support for code block execution
=> feat: Add lua language support for code blocks execution

README.md
=> add code blocks execution to readme

internal/model/model.go
-  removing the first line of the file, if it starts with `#!`
=> ignoring the shebang, to run slideshows easier.

internal/code/code.go, internal/code/code_test.go, internal/model/model.go
Fix the problem that is unable to run multiple code blocks in a single slide.
=> be able to run multiple code blocks in a single slide

internal/model/model.go
Hello,
This is a trial to support word wrapping. Changing the size in View() allows to adjust dynamically to the window width.
I did not test a lot, hence the draft PR.
If you are interested, could you tell me what needs to be tested (inline code & large number of lines maybe ?)
Very cool project by the way ;)
=> Word wrap support

README.md, internal/navigation/navigation.go
- Page up and page down navigation support
=> Added page up and page down navigation

internal/code/code.go, internal/code/execute_test.go, internal/model/model.go
- Use exit code from command, if exists
- Clear `VirtualText` inside `SetPage`
=> Improvements to exit code handling, virtual text reset

cmd/root.go, go.mod, go.sum, internal/model/model.go, internal/navigation/search.go, internal/navigation/search_test.go, styles/styles.go
Hi! 👋
I looked at the bubbles project, and I think it is more user friendly to use `bubbles#TextInput` as a search bar, because with the text input, for example, you have a cursor to go through the letters.
What do you think?
https://user-images.githubusercontent.com/71837281/139705482-b7fa2680-f314-4cc5-a462-9f40e7e14c41.mov
=> feat[search]: use `bubbles#TextInput`

internal/meta/meta.go
Fixes #142
- Lookup `GLAMOUR_THEME` and use if set
=> Respect `GLAMOUR_THEME` if environment variable set

internal/model/model.go, internal/model/tutorial.md, main.go
Fixes #59
- Add `tutorial.md` and run when no arguments are passed to `slides`
=> Slides Tutor

internal/code/code.go, internal/model/model.go
- Yank Code Blocks to clipboard
=> Feat: Yank Code Blocks

examples/preprocess.md
- add example on how to use plantuml in preprocess
=> docs: add example using plantuml

internal/model/model.go
Fixes #182
- Renders tabs as spaces to fix spacing issues
=> fix: indentation problem within code blocks

examples/code_blocks.md, internal/code/languages.go
A small PR to add support for running Julia in code blocks. I tested it with some simple code blocks with imports, functions and such and all seems to go smoothly.
=> Add support for the Julia language

examples/code_blocks.md, internal/code/languages.go
- Adds support for executing C++ code
=> Add support for executing C++ code

examples/code_blocks.md, internal/code/languages.go
Based on [this](https://github.com/maaslalani/slides/pull/225) pull request, I decided to add [Dart](https://dart.dev/) support since I will be using this for a presentation. Please let me know if there is anything else that needs to be done. Thank you!
=> Add dart support

examples/code_blocks.md, internal/code/languages.go
Adds support for [V Programming Language](https://vlang.io/)
- Supported added for v language
=> add vlang support

internal/code/languages.go
- Added support for OCaml code blocks.
=> Add support for OCaml

internal/code/languages.go
Hey, I'd like to use slides for a talk I've to give in a few weeks.
Thought it'd be cool to be able to run Haskell code :)
-  Add haskell to the list of supported languages
=> Add haskell support to languages.go
